### ISSUE TITLE
Upgrade to DAML SDK 100.12.22

### ISSUE THREAD

**Issue by meiersi** [digital-asset/daml-on-x-example#14]
The interfaces in `participant.state.v1.WriteService` have changed between `100.12.22` and `100.12.17`. This ticket serves to document the necessary code changes for integration partners that have based their code off of this example code.

- [ ] perform upgrade
- [ ] document required code change by linking form CHANGELOG to this ticket

FYI: @dajmaki @gleber-da @meiersi-da @mziolekda @gaboraranyossy-da @gerolf-da @bitonic @rautenrieth-da

**Comment by meiersi-da** [comment]
Fixed by #15
