### ISSUE TITLE
i get an  exception  NonMonotonicRecordTimeUpdate

### ISSUE THREAD

**Issue by liangyongfu** [digital-asset/daml-on-x-example#21]
sdk version :0.13.12 
daml-on-x-example:master

in my code， i write  state data to a  file
when i run it at the first time like this：
java -jar target/scala-2.12/damlonx-example.jar   --port 6865 ../iou/quickstart/.daml/dist/quickstart.dar 

it works.

### **when i kill the process  and restart  , i get the exaption  and  it not works any more , can not get the heartbeat update any more**

15:37:07.085 [DamlonxExampleServer-akka.actor.default-dispatcher-5] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-0: Public package uploaded: ab97e77e1116b9d923f77d2568b8721ed651af69734344817f3ebab8cffa4c0e
15:37:07.085 [main] INFO com.daml.ledger.api.server.damlonx.Server$ - DAML LF Engine supports LF versions: 0, 0.dev, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.dev; Transaction versions: 1, 2, 3, 4, 5, 6, 7, 8; Value versions: 1, 2, 3, 4, 5
15:37:07.088 [DamlonxExampleServer-akka.actor.default-dispatcher-5] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-1: Public package uploaded: a5264aaa710fe11a94ac80d71efc1083997ed09f39047888ae1c1d90cc4a549a
15:37:07.092 [DamlonxExampleServer-akka.actor.default-dispatcher-5] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-2: Public package uploaded: 7220d9a38b8b7bd5a9b67149c40e242c488084fd499e0d1a0b5b97721c7933ba
15:37:07.093 [DamlonxExampleServer-akka.actor.default-dispatcher-5] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 1-0: Heartbeat: 2019-07-24T07:36:12.874Z
### **15:37:07.094 [DamlonxExampleServer-akka.actor.default-dispatcher-5] ERROR com.daml.ledger.damlonxexample.ExampleServer$ - Supervision caught exception: java.lang.RuntimeException: Invariant violation: NonMonotonicRecordTimeUpdate**
15:37:07.138 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
15:37:07.139 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
15:37:07.149 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
15:37:07.149 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
15:37:07.158 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
15:37:07.158 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8

**Comment by liangyongfu** [comment]
when i first run the process , logs like this:

15:05:11.248 [main] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - Starting ledger backend at offset 0
15:05:11.368 [main] INFO com.daml.ledger.damlonxexample.ExampleServer$ - Uploading archives ab97e77e1116b9d923f77d2568b8721ed651af69734344817f3ebab8cffa4c0e,a5264aaa710fe11a94ac80d71efc1083997ed09f39047888ae1c1d90cc4a549a,7220d9a38b8b7bd5a9b67149c40e242c488084fd499e0d1a0b5b97721c7933ba...
15:05:11.407 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - CommitActor: processing submission 4CD9FAA9E08634B741...
15:05:11.444 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - CommitActor: committing 4CD9FAA9E08634B741 and 4 updates to store.
15:05:11.454 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - CommitActor: data keys: Set(<ByteString@3eea26f6 size=68>, <ByteString@6a553bf4 size=68>, <ByteString@5953ff7c size=68>, <ByteString@75e6cec3 size=9>)   data values: MapLike.DefaultValuesIterable(<ByteString@1ad49b1f size=160396>, <ByteString@599d892a size=945053>, <ByteString@1ff3257a size=1237218>, <ByteString@5ca06091 size=2342732>)  updates to store.
15:05:11.455 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data key: <ByteString@3eea26f6 size=68>
15:05:11.455 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data value: <ByteString@1ad49b1f size=160396>
15:05:11.455 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data key: <ByteString@6a553bf4 size=68>
15:05:11.455 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data value: <ByteString@599d892a size=945053>
15:05:11.455 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data key: <ByteString@5953ff7c size=68>
15:05:11.455 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data value: <ByteString@1ff3257a size=1237218>
15:05:11.455 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data key: <ByteString@75e6cec3 size=9>
15:05:11.456 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data value: <ByteString@5ca06091 size=2342732>
15:05:11.520 [main] INFO com.daml.ledger.api.server.damlonx.Server$ - DAML LF Engine supports LF versions: 0, 0.dev, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.dev; Transaction versions: 1, 2, 3, 4, 5, 6, 7, 8; Value versions: 1, 2, 3, 4, 5
15:05:11.567 [DamlonxExampleServer-akka.actor.default-dispatcher-13] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-0: Public package uploaded: ab97e77e1116b9d923f77d2568b8721ed651af69734344817f3ebab8cffa4c0e
15:05:11.570 [DamlonxExampleServer-akka.actor.default-dispatcher-13] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-1: Public package uploaded: a5264aaa710fe11a94ac80d71efc1083997ed09f39047888ae1c1d90cc4a549a
15:05:11.573 [DamlonxExampleServer-akka.actor.default-dispatcher-13] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-2: Public package uploaded: 7220d9a38b8b7bd5a9b67149c40e242c488084fd499e0d1a0b5b97721c7933ba
15:05:11.606 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
15:05:11.608 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
15:05:11.625 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
15:05:11.625 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
15:05:11.639 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
15:05:11.639 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
15:05:11.640 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
15:05:11.641 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
15:05:11.641 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
15:05:11.642 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
15:05:11.643 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
15:05:11.643 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
15:05:11.643 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
15:05:11.643 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
15:05:11.643 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
15:05:11.643 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
15:05:11.644 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 1804599296 bytes
15:05:11.644 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
15:05:11.645 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
15:05:11.645 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
15:05:11.650 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
15:05:11.693 [main] INFO com.daml.ledger.api.server.damlonx.Server - Starting plainText server
15:05:11.964 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 28805 (auto-detected)
15:05:11.966 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
15:05:11.966 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
15:05:11.977 [main] DEBUG io.netty.util.NetUtil - Loopback interface: [lo, lo, 0:0:0:0:0:0:0:1%lo] ([lo, lo, 0:0:0:0:0:0:0:1%lo], {})
15:05:11.978 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
15:05:11.981 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 48:4d:7e:ff:fe:a7:c5:12 (auto-detected)
15:05:11.986 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
15:05:11.986 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
15:05:11.994 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
15:05:11.994 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
15:05:12.018 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
15:05:12.018 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
15:05:12.018 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
15:05:12.018 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
15:05:12.019 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
15:05:12.019 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
15:05:12.019 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
15:05:12.019 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
15:05:12.019 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
15:05:12.019 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
15:05:12.019 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
15:05:12.019 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
15:05:12.027 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
15:05:12.027 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
15:05:12.027 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
15:05:12.056 [main] INFO com.daml.ledger.api.server.damlonx.Server - listening on localhost:6865
15:05:16.382 [DamlonxExampleServer-akka.actor.default-dispatcher-13] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 1-0: Heartbeat: 2019-07-24T07:05:16.352Z
15:05:21.372 [DamlonxExampleServer-akka.actor.default-dispatcher-3] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 2-0: Heartbeat: 2019-07-24T07:05:21.352Z
15:05:26.372 [DamlonxExampleServer-akka.actor.default-dispatcher-12] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 3-0: Heartbeat: 2019-07-24T07:05:26.352Z

**Comment by liangyongfu** [comment]
### **when restart the process , the log like this:**

15:37:06.748 [main] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - get init state
15:37:06.819 [main] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - Starting ledger backend at offset 10
15:37:06.937 [main] INFO com.daml.ledger.damlonxexample.ExampleServer$ - Uploading archives ab97e77e1116b9d923f77d2568b8721ed651af69734344817f3ebab8cffa4c0e,a5264aaa710fe11a94ac80d71efc1083997ed09f39047888ae1c1d90cc4a549a,7220d9a38b8b7bd5a9b67149c40e242c488084fd499e0d1a0b5b97721c7933ba...
15:37:06.972 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - CommitActor: processing submission 4CE048283F541A9DF2...
15:37:06.998 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - CommitActor: committing 4CE048283F541A9DF2 and 1 updates to store.
15:37:07.001 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - CommitActor: data keys: Set(<ByteString@2be53b8c size=9>)   data values: MapLike.DefaultValuesIterable(<ByteString@1be97e7d size=62>)  updates to store.
15:37:07.002 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data key: <ByteString@2be53b8c size=9>
15:37:07.002 [DamlonxExampleServer-akka.actor.default-dispatcher-3] ERROR com.daml.ledger.damlonxexample.ExampleInMemoryParticipantState - data value: <ByteString@1be97e7d size=62>
15:37:07.085 [DamlonxExampleServer-akka.actor.default-dispatcher-5] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-0: Public package uploaded: ab97e77e1116b9d923f77d2568b8721ed651af69734344817f3ebab8cffa4c0e
15:37:07.085 [main] INFO com.daml.ledger.api.server.damlonx.Server$ - DAML LF Engine supports LF versions: 0, 0.dev, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.dev; Transaction versions: 1, 2, 3, 4, 5, 6, 7, 8; Value versions: 1, 2, 3, 4, 5
15:37:07.088 [DamlonxExampleServer-akka.actor.default-dispatcher-5] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-1: Public package uploaded: a5264aaa710fe11a94ac80d71efc1083997ed09f39047888ae1c1d90cc4a549a
15:37:07.092 [DamlonxExampleServer-akka.actor.default-dispatcher-5] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 0-2: Public package uploaded: 7220d9a38b8b7bd5a9b67149c40e242c488084fd499e0d1a0b5b97721c7933ba
15:37:07.093 [DamlonxExampleServer-akka.actor.default-dispatcher-5] INFO com.daml.ledger.participant.state.index.v1.impl.reference.ReferenceIndexService - Applying update 1-0: Heartbeat: 2019-07-24T07:36:12.874Z
###**15:37:07.094 [DamlonxExampleServer-akka.actor.default-dispatcher-5] ERROR com.daml.ledger.damlonxexample.ExampleServer$ - Supervision caught exception: java.lang.RuntimeException: Invariant violation: NonMonotonicRecordTimeUpdate**
15:37:07.138 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
15:37:07.139 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
15:37:07.149 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
15:37:07.149 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
15:37:07.158 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
15:37:07.158 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
15:37:07.158 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
15:37:07.159 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
15:37:07.159 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
15:37:07.159 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
15:37:07.159 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
15:37:07.159 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
15:37:07.159 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
15:37:07.159 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
15:37:07.160 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
15:37:07.160 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
15:37:07.160 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 1804599296 bytes
15:37:07.160 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
15:37:07.161 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
15:37:07.161 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
15:37:07.164 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
15:37:07.190 [main] INFO com.daml.ledger.api.server.damlonx.Server - Starting plainText server
15:37:07.364 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 30037 (auto-detected)
15:37:07.366 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
15:37:07.366 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
15:37:07.367 [main] DEBUG io.netty.util.NetUtil - Loopback interface: [lo, lo, 0:0:0:0:0:0:0:1%lo] ([lo, lo, 0:0:0:0:0:0:0:1%lo], {})
15:37:07.368 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
15:37:07.369 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 48:4d:7e:ff:fe:a7:c5:12 (auto-detected)
15:37:07.372 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
15:37:07.372 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
15:37:07.377 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
15:37:07.377 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
15:37:07.393 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
15:37:07.393 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
15:37:07.393 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
15:37:07.393 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
15:37:07.393 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
15:37:07.393 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
15:37:07.393 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
15:37:07.393 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
15:37:07.394 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
15:37:07.394 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
15:37:07.394 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
15:37:07.394 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
15:37:07.399 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
15:37:07.400 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
15:37:07.400 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
15:37:07.415 [main] INFO com.daml.ledger.api.server.damlonx.Server - listening on localhost:6865

**Comment by mziolekda** [comment]
Hi Barry.
The log-lines on our side are a bit lacking, sorry for that. 

The problem you describe happens when the Heartbeats received among the stateUpdates go back in time. There is a check that makes sure that the recordTime field in side Update.Heartbeat is either equal or larger than the previously supplied value i.e. monotonically don decreasing. 
The starting value for this mechanism is delivered in the LedgerInitialConditions record returned from getLedgerInitialConditions.
As a next step, I suggest you log this initial value and then every subsequent heartbeat value that you send. From these logs you should be able to catch the moment when the time goes backwards.

**Comment by liangyongfu** [comment]
thanks  Mziolekda.
 i don't save  initialConditions to files,  so when restart,  the initialConditions RecordTime is when it  started at the second time..  and the history heartbeat  is early then it ...
i solve it by  save initialConditions RecordTime to file..... when restart,,  give the time to 
LedgerInitialConditions   instead of the program start time.
